import { PrecomputedEmbeddingsSchema, type PrecomputedEmbeddings } from '@lab/shared';

import precomputedJson from '../../../../../../content/modules/03-how-llms-work/embeddings-precomputed.json?raw';

/**
 * The shipped embedding vectors — the reason the embeddings tab works on a deployment
 * running `MODEL_PROVIDER=none`, which is every deployment.
 *
 * Imported as `?raw` and `JSON.parse`d rather than as a JSON module. Two reasons, one
 * boring and one not: it keeps `resolveJsonModule` out of the web tsconfig, and parsing a
 * 300 KB string is measurably *faster* than evaluating the equivalent object literal,
 * because the JSON parser does not have to go through the JavaScript grammar. It is also
 * the only way the Zod validation below can be honest — a JSON module would already be a
 * typed object by the time we looked at it.
 *
 * Validation is not paranoia about our own generator. The file is regenerated by
 * `pnpm content:embeddings` against whatever Ollama happens to be installed, and a
 * truncated or half-written vector would otherwise surface as a PCA of `NaN`: a blank
 * scatter plot with no error anywhere. Failing at import time with a path names the
 * problem instead.
 *
 * Parsed once at module scope. It is the same file for every learner and it never
 * changes at runtime.
 */
export const PRECOMPUTED_EMBEDDINGS: PrecomputedEmbeddings = PrecomputedEmbeddingsSchema.parse(
  JSON.parse(precomputedJson),
);

/** The file named by `embeddings.fallbackFile`, checked against what is actually bundled. */
const FILES: Record<string, PrecomputedEmbeddings> = {
  'embeddings-precomputed.json': PRECOMPUTED_EMBEDDINGS,
};

export function bundledEmbeddings(fileName: string): PrecomputedEmbeddings {
  const file = FILES[fileName];
  if (file === undefined) {
    throw new Error(
      `No bundled embeddings file "${fileName}". Known: ${Object.keys(FILES).join(', ')}.`,
    );
  }
  return file;
}

/**
 * The vectors for exactly the words the config asks for, in config order.
 *
 * A word with no vector is dropped rather than defaulted to zeros: `cosineSimilarity`
 * throws on the zero vector (rightly — it has no direction), and a silent row of zeros
 * would drag the PCA mean around and quietly distort every other point. The caller
 * reports the missing words instead.
 */
export function vectorsForWords(
  file: PrecomputedEmbeddings,
  words: readonly string[],
): { vectors: Record<string, number[]>; missing: string[] } {
  const vectors: Record<string, number[]> = {};
  const missing: string[] = [];
  for (const word of words) {
    const vector = file.vectors[word];
    if (vector) vectors[word] = vector;
    else missing.push(word);
  }
  return { vectors, missing };
}
